/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// module.exports = {
//   embeddedSystemsAnalysis: {
//     'Embedded Systems Analysis': [
//       { 'Other Thing': ['embedded/initial_visual_analysis/Disassembly'] },
//     ],
//   },

//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   // tutorialSidebar: [
//   //   {type: 'autogenerated', dirName: '.'},
//   // ],

//   // But you can create a sidebar manually

//   // tutorialSidebar: [
//   //   {
//   //     type: 'category',
//   //     label: 'Embedded Systems Analysis',
//   //     items: [{ mything: [] }],
//   //   },
//   // ],
// };

module.exports = {
  globalSidebar: [
    'Inform',
    { type: 'ref', label: 'Embedded Systems Analysis', id: 'EmbeddedSystemsAnalysis/overview' },
    { type: 'ref', label: 'System Details', id: 'Systems/overview'},
    { type: 'ref', label: 'Tools & Use Cases', id: 'ToolCases/Overview'},
    { type: 'ref', label: 'Workflow & Techniques', id: 'WorkflowAndTechniques/Overview'},
    { type: 'ref', label: 'Third Party Software', id: 'ThirdParty/Overview'},
    //{ type: 'ref', label: 'Visual Studio Code Tips', id: 'VisualStudioCode/Overview' },
  ],
  embeddedSidebar: [{ type: 'autogenerated', dirName: 'EmbeddedSystemsAnalysis' }],
  systemsSideBar: [{type: 'autogenerated', dirName: 'Systems'}],
  toolCasesSideBar: [{type: 'autogenerated', dirName: 'ToolCases'}],
  workflowTechniquesSidebar: [{type: 'autogenerated', dirName: 'WorkflowAndTechniques'}],
  thirdPartySidebar: [{type: 'autogenerated', dirName: 'ThirdParty'}],
  //vscodeSidebar: [{ type: 'autogenerated', dirName: 'VisualStudioCode' }],
  // embeddedSystemsAnalysis: {
  //   'Embedded Systems Analysis': [
  //     {
  //       'Initial Visual Analysis': [
  //         {
  //           type: 'doc',
  //           id: 'intro',
  //           label: 'Label', // Sidebar label text
  //         },
  //       ],
  //     },
  //   ],
  // },
};
