/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  globalSidebar: [
    'Inform',
    { type: 'ref', label: 'Embedded Systems Analysis', id: 'EmbeddedSystemsAnalysis/overview' },
    { type: 'ref', label: 'System Details', id: 'Systems/overview' },
    { type: 'ref', label: 'Problem Book', id: 'ProblemBook/Overview' },
    { type: 'ref', label: 'Env & Workflow', id: 'EnvAndWorkflow/Overview' },
    { type: 'ref', label: 'Collections', id: 'Collections/Overview' },
    { type: 'ref', label: 'Third Party Software', id: 'ThirdParty/Overview' },
    //{ type: 'ref', label: 'Visual Studio Code Tips', id: 'VisualStudioCode/Overview' },
  ],
  embeddedSidebar: [{ type: 'autogenerated', dirName: 'EmbeddedSystemsAnalysis' }],
  systemsSideBar: [{ type: 'autogenerated', dirName: 'Systems' }],
  problemBookSideBar: [{ type: 'autogenerated', dirName: 'ProblemBook' }],
  envAndWorkflowSidebar: [{ type: 'autogenerated', dirName: 'EnvAndWorkflow' }],
  collectionsSideBar: [{ type: 'autogenerated', dirName: 'Collections' }],
  thirdPartySidebar: [{ type: 'autogenerated', dirName: 'ThirdParty' }],
  //vscodeSidebar: [{ type: 'autogenerated', dirName: 'VisualStudioCode' }],
  // embeddedSystemsAnalysis: {
  //   'Embedded Systems Analysis': [
  //     {
  //       'Initial Visual Analysis': [
  //         {
  //           type: 'doc',
  //           id: 'intro',
  //           label: 'Label', // Sidebar label text
  //         },
  //       ],
  //     },
  //   ],
  // },
};

export default sidebars;
